### ISSUE TITLE
Mistaken Balance Druid item

### ISSUE THREAD

**Issue by Har4oo** [stlevkov/BIS_Core#1]
Hello

I've been exploring the addon. Thanks a lot, needed something like that!

The Balance Druid second finger slot is mistaken with **[this item](https://www.wowhead.com/wotlk/item=50613/crushing-coldwraith-belt)**. 

Thanks in advance!

**Comment by stlevkov** [comment]
Thanks for spotting this out! The add-on is completely fresh so any help fulfilling the bis and pre-bis lists is much appreciated.
